### ISSUE TITLE
Can't run imgopt within php script

### ISSUE THREAD

**Issue by ozozm** [kormoc/imgopt#11]
Hi kormac, I look forward to trying your software.

I need to run imgopt within a php script. I tried the following but had no joy, can you help please?
```
<?php

$target_dir = "../images/";
	
$newFileName = basename($_FILES["fileToUpload"]["name"]);
	

$target_dir = escapeshellarg($target_dir);
	
$newFileName = escapeshellarg($newFileName);

	
system("imgopt $newFileName $target_dir");

?>
```

**Comment by ozozm** [comment]
I found this, but it doesnt seem to do anything. Is there a way to test that imgopt is installed correctly on the server? Either that or I'm way off on the shell command? Where would they even have got "jpegtran -copy none -optimize -progressive -outfile" from? Is there some documentation anywhere?

`jpegtran -copy none -optimize -progressive -outfile output.jpg input.jpg`

So I tried to use the follwing..

```
<?php

$input = "../images/image.jpg";
$input = escapeshellarg($input);

$output = "../images/image.jpg" . "_imgopt";
$output = escapeshellarg($output_dir);
	
system("jpegtran -copy none -optimize -progressive -outfile $output $input");

?>
```

Can you help me out here please? I have tried all manner of things to get this to work :(

**Comment by kormoc** [comment]
The only docs I have is the main README.md file at https://github.com/kormoc/imgopt/blob/master/README.md

jpegtran is part of libjpeg, so if you install that, your `system("jpegtran -copy none -optimize -progressive -outfile $output $input");` should work and you don't need the entire imgopt script. The readme does document the other tools and the package names where you can get to them.

That said, these days using something like https://modpagespeed.com/ or one of the image compression webservices is often better then using a script like this, as their tooling tends to get better compression then even imgopt gets.
